apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
volumeBindingMode: Immediate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo
 